/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.bookmarks.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Bookmark service. Represents a row in the &quot;BOOKMARK_Bookmark&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.bookmarks.model.impl.BookmarkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.bookmarks.model.impl.BookmarkImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Bookmark
 * @generated
 */
@ProviderType
public interface BookmarkModel
	extends BaseModel<Bookmark>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bookmark model instance should use the {@link Bookmark} interface instead.
	 */

	/**
	 * Returns the primary key of this bookmark.
	 *
	 * @return the primary key of this bookmark
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bookmark.
	 *
	 * @param primaryKey the primary key of this bookmark
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this bookmark.
	 *
	 * @return the uuid of this bookmark
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this bookmark.
	 *
	 * @param uuid the uuid of this bookmark
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the bookmark ID of this bookmark.
	 *
	 * @return the bookmark ID of this bookmark
	 */
	public long getBookmarkId();

	/**
	 * Sets the bookmark ID of this bookmark.
	 *
	 * @param bookmarkId the bookmark ID of this bookmark
	 */
	public void setBookmarkId(long bookmarkId);

	/**
	 * Returns the group ID of this bookmark.
	 *
	 * @return the group ID of this bookmark
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this bookmark.
	 *
	 * @param groupId the group ID of this bookmark
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this bookmark.
	 *
	 * @return the company ID of this bookmark
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this bookmark.
	 *
	 * @param companyId the company ID of this bookmark
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this bookmark.
	 *
	 * @return the user ID of this bookmark
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this bookmark.
	 *
	 * @param userId the user ID of this bookmark
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this bookmark.
	 *
	 * @return the user uuid of this bookmark
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this bookmark.
	 *
	 * @param userUuid the user uuid of this bookmark
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this bookmark.
	 *
	 * @return the user name of this bookmark
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this bookmark.
	 *
	 * @param userName the user name of this bookmark
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this bookmark.
	 *
	 * @return the create date of this bookmark
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this bookmark.
	 *
	 * @param createDate the create date of this bookmark
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this bookmark.
	 *
	 * @return the modified date of this bookmark
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this bookmark.
	 *
	 * @param modifiedDate the modified date of this bookmark
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this bookmark.
	 *
	 * @return the title of this bookmark
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this bookmark.
	 *
	 * @param title the title of this bookmark
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this bookmark.
	 *
	 * @return the description of this bookmark
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this bookmark.
	 *
	 * @param description the description of this bookmark
	 */
	public void setDescription(String description);

	/**
	 * Returns the url of this bookmark.
	 *
	 * @return the url of this bookmark
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this bookmark.
	 *
	 * @param url the url of this bookmark
	 */
	public void setUrl(String url);

}